### PR TITLE
changed the URL path of SWOC

### PR DESCRIPTION
**Pull request by dineshkumar12004**
# Related Issue
*Script Winter of Code SWOC Link is dead #27*

# Summary
*Fixed the URL path of swoc*

### CODE REVIEW

**Comment by vibalijoshi** [comment]
Hey @dineshkumar12004 can you change the link in the opportunties.ts file? Thanks for pointing out : D

**Comment by vibalijoshi** [comment]
https://github.com/vibalijoshi/List-of-Opportunities/blob/main/src/logic/opportunities.ts

**Comment by dineshkumar12004** [comment]
> Hey @dineshkumar12004 can you change the link in the opportunties.ts file? Thanks for pointing out : D

I have already changed it :)

image

**Comment by vibalijoshi** [comment]
Ohh my bad! Thank you so much for your contribution! ✨

**Pull request merged**
